#!/bin/sh


# Function to create a transparent Wx1 px XPM icon
create_xpm_icon () {
    timestamp=$(date)
    pixels=$(for i in `seq $1`; do echo -n "."; done)

    cat << EOF > "$2"
/* XPM *
static char * trayer_pad_xpm[] = {
/* This XPM icon is used for padding in xmobar to */
/* leave room for trayer-srg. It is dynamically   */
/* updated by by trayer-padding-icon.sh which is run  */
/* by xmobar.                                     */
/* Created: ${timestamp} */
/* <w/cols>  <h/rows>  <colors>  <chars per pixel> */
"$1 1 1 1",
/* Colors (none: transparent) */
". c none",
/* Pixels */
"$pixels"
};
EOF
}

if [ "$1" == "music" ] ; then
 MPCIsPlaying="$(mpc status | grep playing)"
 MPCIsPaused="$(mpc status | grep paused)"

 if [ "$MPCIsPaused" == "" ] ; then
   if [ "$MPCIsPlaying" == "" ] ; then
     echo "Stopped"
   else
     mpc --format '%artist% - %title%' | head -1
   fi
 else
   echo "Paused"
 fi
elif [ "$1" == "padding" ] ; then
 width=$(xprop -name panel | grep 'program specified minimum size' | cut -d ' ' -f 5) # Width of the trayer window
 iconfile="/tmp/trayer-padding-${width}px.xpm" # Icon file name

 # If the desired icon does not exist create it
 if [ ! -f $iconfile ]; then
   create_xpm_icon $width $iconfile
 fi

 # Output the icon tag for xmobar
 if [ $width = 12 ] ; then
   echo " "
 else
   echo "|<icon=${iconfile}/>"
 fi
elif [ "$1" == "weather" ] ; then
 WeatherIcon="$(curl 'v2t.wttr.in/?format='%c'')"
 echo "$(curl 'v2t.wttr.in/?format='%t'')" ${WeatherIcon::-2}
else
 echo "Wrong Command"
fi
