#!/bin/sh

if [ "$1" == "up" ] ; then
 brightnessctl s 5%+
elif [ "$1" == "down" ] ; then
 brightnessctl s 5%-
else
 echo "Wrong Command"
fi

Brightness=$(( $(brightnessctl g) * 100 / $(brightnessctl m) ))
notify-send -h string:x-canonical-private-synchronous:sys-notify -h int:value:"$Brightness" -t 2000 "Brightness: $Brightness%"


if [ $Brightness == 0 ] ; then
 echo "Don't Play Sound"
elif [ $Brightness == 100 ] ; then
 echo "Don't Play Sound"
else
 setsid -f mpv --no-video ~/.local/share/sounds/key.mp3
fi
