#!/bin/sh

FileDate="$(date '+%Y%m%d%H%M%S')"

setsid -f mpv --no-video ~/.local/share/sounds/menu.open.mp3

if [ "$1" == "rectangle" ] ; then
	grim -g "$(slurp)" ~/sync/pics/screenshots/"$FileDate".png
elif [ "$1" == "fullscreen" ] ; then
	shotgun -o ~/sync/pics/screenshots/"$FileDate".png
else
    echo "No File Type specified"
    return 1
fi

setsid -f mpv --no-video ~/.local/share/sounds/screenshot.mp3
setsid -f swappy -f ~/sync/pics/screenshots/"$FileDate".png
