#!/bin/sh

if [ "$1" == "up" ] ; then
 pamixer -u
 pamixer -i 5
elif [ "$1" == "down" ] ; then
 pamixer -u
 pamixer -d 5
elif [ "$1" == "mute" ] ; then
 pamixer -t
else
 echo "Wrong Command"
fi

Volume="$(pamixer --get-volume)"
if [ "$(pamixer --get-mute)" == "true" ] ; then
 notify-send -h string:x-canonical-private-synchronous:sys-notify -h int:value:"0" -t 2000 "Volume: [M]"
else
 notify-send -h string:x-canonical-private-synchronous:sys-notify -h int:value:"$Volume" -t 2000 "Volume: $Volume%"
fi

if [ $Volume == 0 ] ; then
 echo "Don't Play Sound"
elif [ $Volume == 100 ] ; then
 echo "Don't Play Sound"
else
 setsid -f mpv --no-video ~/.local/share/sounds/hotkey.mp3
fi
